version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nms_app
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      DATABASE_URL:          postgresql+psycopg2://monitoring_man:admin123@127.0.0.1:5433/monitoring_db
      REDIS_URL:             redis://127.0.0.1:6379/0
      SESSION_COOKIE_SECURE: "False"
      WEB_OPEN_BROWSER:      "0"
      WEB_HOST:              "0.0.0.0"
      WEB_PORT:              "5001"
      WORKER_SCOPES:         "admin__global:24h:active:200,admin__global:30d:active:200"
    volumes:
      - app_instance:/app/instance   # persists SQLite fallback + uploads

volumes:
  app_instance:
