version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: monitoring_db
      POSTGRES_USER: monitoring_man
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg2://monitoring_man:admin123@db:5432/monitoring_db
      SESSION_COOKIE_SECURE: "False"
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata:
