from __future__ import annotations

import ipaddress
import logging
import re
from datetime import datetime

from sqlalchemy import func

from extensions import db
from models.audit_log import AuditLog
from models.device import Device
from models.device_identity_link import DeviceIdentityLink
from models.scan_history import DeviceScanHistory
from services.dashboard_cache_service import invalidate_dashboard_server_views
from services.device_identity import compute_subnet_cidr
from utils.server_health import is_server_device

logger = logging.getLogger(__name__)

FATAL_SYNC_REASON_CODES = {"IP_COLLISION", "MAC_MISMATCH", "LINK_CONFLICT"}


def _normalize_ip(ip_value):
    if not ip_value:
        return None
    try:
        parsed = ipaddress.ip_address(str(ip_value).strip())
    except ValueError:
        return None
    return str(parsed)


def _normalize_mac(mac_value):
    if mac_value is None:
        return None
    cleaned = re.sub(r"[^0-9A-Fa-f]", "", str(mac_value).strip())
    if len(cleaned) != 12:
        return None
    cleaned = cleaned.upper()
    return ":".join(cleaned[index : index + 2] for index in range(0, 12, 2))


def _should_rename_autogenerated_name(device_name, previous_ip):
    if not device_name or not previous_ip:
        return False
    return str(device_name).strip() == f"Device-{previous_ip}"


def _active_links_for_tracked_device(tracked_device_id: int):
    return (
        DeviceIdentityLink.query.filter_by(tracked_device_id=int(tracked_device_id), is_active=True)
        .order_by(DeviceIdentityLink.id.desc())
        .all()
    )


def sync_linked_inventory_ip(*, tracked_device, old_ip, new_ip, reason, changed_at_utc=None, session=None) -> dict:
    tracked_device_id = int(getattr(tracked_device, "id", 0) or 0)
    normalized_new_ip = _normalize_ip(new_ip)
    normalized_old_ip = _normalize_ip(old_ip)
    changed_at = changed_at_utc or datetime.utcnow()

    result = {
        "updated": False,
        "reason_code": "NO_CHANGE",
        "device_id": None,
        "tracked_device_id": tracked_device_id or None,
        "link_id": None,
        "fatal": False,
    }

    if not tracked_device_id or not normalized_new_ip or normalized_new_ip == normalized_old_ip:
        return result

    active_links = _active_links_for_tracked_device(tracked_device_id)
    if not active_links:
        result["reason_code"] = "NO_ACTIVE_LINK"
        logger.info("[InventorySync] skipped reason=%s tracked_device_id=%s", result["reason_code"], tracked_device_id)
        return result

    if len(active_links) != 1:
        result["reason_code"] = "LINK_CONFLICT"
        result["fatal"] = True
        logger.warning("[InventorySync] skipped reason=%s tracked_device_id=%s active_links=%s", result["reason_code"], tracked_device_id, len(active_links))
        return result

    link = active_links[0]
    result["link_id"] = int(link.id)
    inventory_query = Device.query.filter(Device.device_id == int(link.device_id))
    backend_name = db.engine.url.get_backend_name()
    if backend_name == "postgresql":
        inventory_query = inventory_query.with_for_update()
    device = inventory_query.first()
    result["device_id"] = int(device.device_id) if device else None

    if device is None:
        result["reason_code"] = "NO_ACTIVE_LINK"
        return result

    if not is_server_device(getattr(device, "device_type", None)):
        result["reason_code"] = "NON_SERVER_DEVICE"
        logger.info(
            "[InventorySync] skipped reason=%s tracked_device_id=%s device_id=%s",
            result["reason_code"],
            tracked_device_id,
            device.device_id,
        )
        return result

    tracked_mac = _normalize_mac(getattr(tracked_device, "mac_address", None))
    linked_mac = _normalize_mac(getattr(link, "normalized_mac", None))
    if tracked_mac and linked_mac and tracked_mac != linked_mac:
        result["reason_code"] = "MAC_MISMATCH"
        result["fatal"] = True
        logger.warning(
            "[InventorySync] skipped reason=%s tracked_device_id=%s device_id=%s link_id=%s old_ip=%s new_ip=%s",
            result["reason_code"],
            tracked_device_id,
            device.device_id,
            link.id,
            normalized_old_ip,
            normalized_new_ip,
        )
        return result

    current_device_ip = _normalize_ip(getattr(device, "device_ip", None))
    if current_device_ip == normalized_new_ip:
        result["reason_code"] = "NO_CHANGE"
        return result

    collision = (
        Device.query.filter(func.lower(Device.device_ip) == normalized_new_ip.lower(), Device.device_id != device.device_id)
        .first()
    )
    if collision is not None:
        # A collision device with no real MAC and no active tracking binding is a
        # weak IP-scan-only record that got superseded when the real device identified
        # itself via MAC/UUID.  Clear its stale IP so the MAC-identified device can
        # claim the address instead of hard-failing with 409.
        collision_mac = _normalize_mac(getattr(collision, "macaddress", None))
        collision_has_tracking = (
            DeviceIdentityLink.query.filter_by(
                device_id=int(collision.device_id), is_active=True
            ).first()
            is not None
        )
        if not collision_mac and not collision_has_tracking:
            logger.warning(
                "[InventorySync] clearing stale IP-scan collision device_id=%s ip=%s "
                "to allow tracked_device_id=%s (device_id=%s) to claim it",
                collision.device_id,
                normalized_new_ip,
                tracked_device_id,
                device.device_id,
            )
            collision.device_ip = None
            db.session.flush()
        else:
            result["reason_code"] = "IP_COLLISION"
            result["fatal"] = True
            logger.warning(
                "[InventorySync] skipped reason=%s tracked_device_id=%s device_id=%s collision_device_id=%s link_id=%s old_ip=%s new_ip=%s",
                result["reason_code"],
                tracked_device_id,
                device.device_id,
                collision.device_id,
                link.id,
                normalized_old_ip,
                normalized_new_ip,
            )
            return result

    previous_device_ip = current_device_ip
    device.device_ip = normalized_new_ip
    device.subnet_cidr = compute_subnet_cidr(normalized_new_ip)
    device.updated_at = changed_at
    if _should_rename_autogenerated_name(device.device_name, previous_device_ip):
        device.device_name = f"Device-{normalized_new_ip}"
    if previous_device_ip and previous_device_ip != normalized_new_ip:
        DeviceScanHistory.query.filter_by(device_ip=previous_device_ip).update(
            {"device_ip": normalized_new_ip},
            synchronize_session=False,
        )
    db.session.flush()

    db.session.add(
        AuditLog(
            user_id=None,
            username="system",
            user_role="system",
            action="update",
            entity_type="device",
            entity_id=int(device.device_id),
            entity_name=device.device_name,
            description=f"Inventory IP synced from tracked device {tracked_device_id}: {previous_device_ip or 'N/A'} -> {normalized_new_ip}",
            changes={
                "sync_reason": reason,
                "tracked_device_id": tracked_device_id,
                "link_id": int(link.id),
                "old_ip": previous_device_ip,
                "new_ip": normalized_new_ip,
            },
        )
    )

    result["updated"] = True
    result["reason_code"] = "UPDATED"
    try:
        result["cache_invalidation"] = invalidate_dashboard_server_views(device_id=device.device_id)
    except Exception as exc:
        logger.warning("[InventorySync] cache invalidation failed device_id=%s error=%s", device.device_id, exc)

    logger.info(
        "[InventorySync] synced tracked_device_id=%s device_id=%s link_id=%s old_ip=%s new_ip=%s",
        tracked_device_id,
        device.device_id,
        link.id,
        previous_device_ip,
        normalized_new_ip,
    )
    return result
